platform :ios, "8.0"

target 'textViewInCell'
pod 'MBProgressHUD', '0.9.2'
pod 'Masonry', '~> 0.6.1'
pod 'SDWebImage'
pod 'AFNetworking', '~> 2.3.1'
pod 'Reachability', '~> 3.1.1'
pod 'JSONModel'
pod 'WebViewJavascriptBridge', '4.1.5'
pod 'ReactiveCocoa', '2.4.7'
pod 'MJRefresh', '3.1.9’
pod 'FMDB'


